### ISSUE TITLE
use of with_serialization_context within a loop

### ISSUE THREAD

**Issue by ChristosT** [mochi-hpc/mochi-thallium#5]
Hi !

Building upon example 16 I noticed that repeatedly using RPCs with a serialization context leads to a segmentation fault.
In particular, by adding a for-loop on the client side:
```cpp
     // attach a serialization context to serialize the input
+    for(int i = 0 ; i < 100 ; i++)
+    {
     auto callable = process.on(server)
                            .with_serialization_context(std::ref(q), d);
     auto response = callable(p1, p2);
     // attach a serialization context to deserialize the output
     point r = response.with_serialization_context(std::ref(q), d);
+    }
```
the client exits with a segmentation fault
```
Thread 1 "16_context_clie" received signal SIGSEGV, Segmentation fault.
HG_Core_reset (handle=0x55555573b460, addr=addr@entry=0x555555594b90, id=id@entry=1009057792)
    at /tmp/christos.tsolakis/spack-stage/spack-stage-mercury-2.0.1-x6nqqjy2weylioqvq46pv3xlx7b33vwt/spack-src/src/mercury_core.c:4935
4935    /tmp/christos.tsolakis/spack-stage/spack-stage-mercury-2.0.1-x6nqqjy2weylioqvq46pv3xlx7b33vwt/spack-src/src/mercury_core.c: No such file or directory.
(gdb) bt
#0  HG_Core_reset (handle=0x55555573b460, addr=addr@entry=0x555555594b90, id=id@entry=1009057792) at /tmp/christos.tsolakis/spack-stage/spack-stage-mercury-2.0.1-x6nqqjy2weylioqvq46pv3xlx7b33vwt/spack-src/src/mercury_core.c:4935
#1  0x00007ffff7f864a5 in HG_Reset (handle=0x55555573bcc0, addr=addr@entry=0x555555594b90, id=id@entry=1009057792) at /tmp/christos.tsolakis/spack-stage/spack-stage-mercury-2.0.1-x6nqqjy2weylioqvq46pv3xlx7b33vwt/spack-src/src/mercury.c:1686
#2  0x00007ffff7fb6455 in __margo_handle_cache_get (mid=mid@entry=0x555555723210, addr=addr@entry=0x555555594b90, id=id@entry=1009057792, handle=handle@entry=0x7fffffffdb70) at src/margo-handle-cache.c:84
#3  0x00007ffff7fae52f in margo_create (mid=0x555555723210, addr=0x555555594b90, id=1009057792, handle=0x7fffffffdb70) at src/margo-core.c:742
#4  0x000055555555c1d8 in thallium::callable_remote_procedure_with_context<>::callable_remote_procedure_with_context(std::weak_ptr<thallium::detail::engine_impl>, unsigned long, thallium::endpoint const&, bool, unsigned short, std::tuple<> const&) (this=0x7fffffffdb60, 
    e=std::weak_ptr<struct thallium::detail::engine_impl> (empty) = {...}, id=1009057792, ep=..., ignore_resp=false, provider_id=0, context=empty std::tuple)
    at /home/christos.tsolakis/mochi-thallium/src/../include/thallium/callable_remote_procedure.hpp:446
#5  0x000055555555a250 in thallium::remote_procedure::on (this=0x7fffffffdac0, ep=...) at /home/christos.tsolakismochi-thallium/src/../include/thallium/remote_procedure.hpp:127
#6  0x0000555555558f5b in main (argc=2, argv=0x7fffffffdcf8) at /home/christos.tsolakis/mochi-thallium/examples/16_context/client.cpp:28
```
Removing the serialization context removes the issue. 
Attached is a slightly modified version of  example 16 , enable/disable `USE_CONTEXT` in `point.hpp"  to test both with and without serialization context.
[example_16.patch](https://gist.github.com/ChristosT/72b192e874148db86a14c7f718fb51f1)

**Comment by mdorier** [comment]
Good catch! Thanks for reporting it. That's corrected and committed on the main branch.

**Comment by ChristosT** [comment]
Thanks for the quick reply !
